### ISSUE TITLE
Statistics responses only received during first data stream after server startup

### ISSUE THREAD

**Issue by earsnot** [jetperch/pyjoulescope_server#4]
The async statistics frames are only being received during the first data stream after server startup.
I have tested that this is the case with both the example client.py and my own application.
The server reports that it is transmitting the statistics frames but nothing is being received.

**Comment by mliberty1** [comment]
Here are my steps to repeat this issue:

    c:\tmp>pip3 install -U pyjoulescope_driver joulescope joulescope_server
    c:\tmp>python -VV
    Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
    c:\tmp>python -m joulescope_server

And then in another console, I run:

    c:\tmp>python -m joulescope_server client

I see `current` and `voltage` lines along with `INFO:2022-12-09 08:35:55,621:client.py:59:joulescope_server.client:async: {'type': 'statistics', 'phase': 'async', ...` lines

If I run the same client command again, I do not see the async statistics lines, but I still see `current` and `voltage`.  Restarting the server fixes the issue for the next client, so the issue is likely host-side, not JS220 instrument-side.  The server console does display this:

```text
INFO:2022-12-09 08:39:55,227:server.py:373:joulescope_server.server:send: {"id": 7, "type": "start", "phase": "rsp", "device": "JS220-000024", "data": null, "status": 200, "status_msg": "Success"}
INFO:2022-12-09 08:39:55,242:sample_buffer.py:110:joulescope.v1.sample_buffer.current_range:add -> auto clear
INFO:2022-12-09 08:39:55,243:sample_buffer.py:124:joulescope.v1.sample_buffer.current_range:skip head=None, sample_id=1805782908, sample_id_orig=3611565816, sz=100800
INFO:2022-12-09 08:39:55,246:sample_buffer.py:110:joulescope.v1.sample_buffer.gpi0:add -> auto clear
INFO:2022-12-09 08:39:55,246:sample_buffer.py:124:joulescope.v1.sample_buffer.gpi0:skip head=None, sample_id=1805786688, sample_id_orig=3611573376, sz=100800
INFO:2022-12-09 08:39:55,280:sample_buffer.py:110:joulescope.v1.sample_buffer.gpi1:add -> auto clear
INFO:2022-12-09 08:39:55,280:sample_buffer.py:124:joulescope.v1.sample_buffer.gpi1:skip head=None, sample_id=1805817936, sample_id_orig=3611635872, sz=100800
INFO:2022-12-09 08:39:55,618:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:56,116:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:56,618:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:57,118:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:57,617:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:58,116:server.py:258:joulescope_server.server:_statistics_fn JS220-000024
INFO:2022-12-09 08:39:58,245:server.py:354:joulescope_server.server:recv: {"id": 8, "type": "stop", "phase": "req", "device": "JS220-000024"}
```

Note the `_statistics_fn` callbacks, so the server is receiving this data, so the JS220 → pyjoulescope_driver → joulescope → joulescope_server path seems to work.

Adding in some debug logging that prints id(self) of the `ClientManager` shows that these `_statistics_fn` callbacks occur with the first, now closed, `ClientManager` instance.

I will keep investigating.

**Comment by mliberty1** [comment]
Statistics should now work on subsequent client sessions with joulescope_server 0.1.5 and newer.  Upgrade to the newest version:

    pip install -U joulescope_server

Please reopen the issue if you still see the problem!

**Comment by earsnot** [comment]
it works for me too <3
